FROM python:3.14-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --all-extras
EXPOSE 8000
CMD uv sync --frozen --all-extras && .venv/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
