FROM python:3.14-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen
EXPOSE 8000
CMD uv sync --frozen && .venv/bin/uvicorn main:app --reload --host 0.0.0.0 --port 8000