"""initial_schema

Revision ID: 7a7ac1a609d0
Revises: 
Create Date: 2026-08-26 07:46:07.176387
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a7ac1a609d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('new_email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens'))
    )
    op.create_index('ix_email_verification_tokens_token_hash', 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('max_admin_users', sa.Integer(), nullable=False),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('max_active_projects', sa.Integer(), nullable=False),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_plans_name'))
    )
    op.create_table('plan_feature_defaults',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_feature_defaults_plan_id_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_feature_defaults')),
    sa.UniqueConstraint('plan_id', 'key', name='uq_plan_feature_defaults_key')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'SUSPENDED', 'CANCELLED', name='tenantstatus'), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_tenants_plan_id_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('SUPER_ADMIN', 'ADMIN_USER', 'CLIENT_USER', 'SYSTEM', name='actortype'), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_type', sa.Enum('COMPANY', 'INDIVIDUAL', name='clienttype'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='clientstatus'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_clients_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=False)
    op.create_table('invoice_number_sequences',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('format_template', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_invoice_number_sequences_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_invoice_number_sequences'))
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('NEW_COMMENT', 'INVOICE_ISSUED', 'PAYMENT_RECEIVED', 'MILESTONE_COMPLETED', 'REFUND_RECORDED', 'ADVANCE_APPLIED', 'PROJECT_CREATED', name='notificationeventtype'), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'INAPP', name='notificationchannel'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notification_preferences_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', 'user_type', 'event_type', 'channel', name='uq_notification_preferences_user_event_channel')
    )
    op.create_index('ix_notification_preferences_user_id', 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('NEW_COMMENT', 'INVOICE_ISSUED', 'PAYMENT_RECEIVED', 'MILESTONE_COMPLETED', 'REFUND_RECORDED', 'ADVANCE_APPLIED', 'PROJECT_CREATED', name='notificationeventtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notifications_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_roles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_name')
    )
    op.create_index('uq_roles_system_name', 'roles', ['name'], unique=True, postgresql_where=sa.text('tenant_id IS NULL'))
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_services_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_tenant_id'), 'services', ['tenant_id'], unique=False)
    op.create_table('tenant_feature_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_feature_flags_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_feature_flags')),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_tenant_feature_flags_key')
    )
    op.create_table('tenant_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('permission_level', sa.Enum('SUPER_ADMIN_ONLY', 'TENANT_ADMIN_EDITABLE', 'TENANT_ADMIN_VIEWABLE', name='permissionlevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_settings_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_settings')),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_tenant_settings_key')
    )
    op.create_table('tenant_smtp_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_ciphertext', sa.Text(), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.Enum('NONE', 'STARTTLS', 'SSL', name='smtpsecuritymode'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_smtp_configs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_smtp_configs')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_smtp_configs_tenant_id'))
    )
    op.create_table('tenant_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', name='billingcycle'), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_tenant_subscriptions_plan_id_plans')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_subscriptions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_subscriptions')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_subscriptions_tenant_id'))
    )
    op.create_table('user_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_activities_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activities'))
    )
    op.create_index('ix_user_activities_user_id', 'user_activities', ['user_id'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pending_email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'EMPLOYEE', name='adminuserrole'), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_admin_users_role_id_roles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_admin_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index('ix_admin_users_email', 'admin_users', ['email'], unique=True)
    op.create_table('client_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pending_email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_primary_billing_contact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_users_client_id_clients')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_client_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_users'))
    )
    op.create_index('ix_client_users_client_id', 'client_users', ['client_id'], unique=False)
    op.create_index('ix_client_users_email', 'client_users', ['email'], unique=True)
    op.create_table('milestone_step_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('expected_duration_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_milestone_step_templates_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone_step_templates'))
    )
    op.create_index(op.f('ix_milestone_step_templates_service_id'), 'milestone_step_templates', ['service_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'action', 'resource', name='uq_role_permissions_role_action_resource')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('client_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_invites_client_id_clients')),
    sa.ForeignKeyConstraint(['invited_by'], ['admin_users.id'], name=op.f('fk_client_invites_invited_by_admin_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_client_invites_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_invites'))
    )
    op.create_index('ix_client_invites_client_email', 'client_invites', ['client_id', 'email'], unique=False)
    op.create_index('ix_client_invites_token_hash', 'client_invites', ['token_hash'], unique=True)
    op.create_table('client_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['admin_users.id'], name=op.f('fk_client_notes_author_id_admin_users')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_notes_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_notes'))
    )
    op.create_table('client_password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_user_id'], ['client_users.id'], name=op.f('fk_client_password_reset_tokens_client_user_id_client_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_password_reset_tokens'))
    )
    op.create_index('ix_client_password_reset_tokens_token_hash', 'client_password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'EMPLOYEE', name='inviterole'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['admin_users.id'], name=op.f('fk_invites_invited_by_admin_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_invites_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites'))
    )
    op.create_index('ix_invites_token', 'invites', ['token'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], name=op.f('fk_password_reset_tokens_created_by_admin_users')),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name=op.f('fk_password_reset_tokens_user_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index('ix_password_reset_tokens_token_hash', 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('auto_invoice', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discounttype'), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount_updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_projects_client_id_clients')),
    sa.ForeignKeyConstraint(['discount_updated_by'], ['admin_users.id'], name=op.f('fk_projects_discount_updated_by_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['admin_users.id'], name=op.f('fk_projects_owner_id_admin_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projects_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('author_type', sa.Enum('TENANT_ADMIN', 'TENANT_MANAGER', 'TENANT_EMPLOYEE', 'CLIENT_USER', name='commentauthortype'), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_comments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    op.create_table('file_folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Enum('USER', 'TENANT', 'PROJECT', name='filescope'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['file_folders.id'], name=op.f('fk_file_folders_parent_id_file_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_file_folders_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_file_folders_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_folders'))
    )
    op.create_index(op.f('ix_file_folders_tenant_id'), 'file_folders', ['tenant_id'], unique=False)
    op.create_index('uq_file_folders_tenant_parent_scope_name_project_creator', 'file_folders', ['tenant_id', 'parent_id', 'scope', 'name', 'project_id', sa.literal_column("COALESCE(created_by_id, '00000000-0000-0000-0000-000000000000')")], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'VOID', name='invoicestatus'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_invoices_project_id_projects')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_invoices_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('tenant_id', 'invoice_number', name='uq_invoices_tenant_invoice_number')
    )
    op.create_index(op.f('ix_invoices_project_id'), 'invoices', ['project_id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('project_services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', name='projectservicestatus'), nullable=False),
    sa.Column('price_at_attachment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_services_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_project_services_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_services')),
    sa.UniqueConstraint('project_id', 'service_id', name='uq_project_services_project_id_service_id')
    )
    op.create_index(op.f('ix_project_services_project_id'), 'project_services', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_services_service_id'), 'project_services', ['service_id'], unique=False)
    op.create_table('advances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_advances_client_id_clients')),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['invoices.id'], name=op.f('fk_advances_source_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_advances_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advances'))
    )
    op.create_index(op.f('ix_advances_client_id'), 'advances', ['client_id'], unique=False)
    op.create_index(op.f('ix_advances_tenant_id'), 'advances', ['tenant_id'], unique=False)
    op.create_table('file_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.Enum('USER', 'TENANT', 'PROJECT', name='filescope'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['file_folders.id'], name=op.f('fk_file_assets_folder_id_file_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_file_assets_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_file_assets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_file_assets_storage_key'))
    )
    op.create_index(op.f('ix_file_assets_folder_id'), 'file_assets', ['folder_id'], unique=False)
    op.create_index(op.f('ix_file_assets_tenant_id'), 'file_assets', ['tenant_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('project_service_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_service_id'], ['project_services.id'], name=op.f('fk_invoice_line_items_project_service_id_project_services')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_invoice_line_items_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items'))
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('CHARGE', 'PAYMENT', 'REFUND', name='ledgerentrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('PROJECT_SERVICE', 'TRANSACTION', 'MANUAL_ADJUSTMENT', name='ledgersourcetype'), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_ref', sa.Uuid(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], name=op.f('fk_ledger_entries_created_by_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_ref'], ['invoices.id'], name=op.f('fk_ledger_entries_invoice_ref_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ledger_entries_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index('ix_ledger_entries_project_date', 'ledger_entries', ['project_id', 'entry_date'], unique=False)
    op.create_index('ix_ledger_entries_project_type', 'ledger_entries', ['project_id', 'type'], unique=False)
    op.create_table('project_milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('project_service_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', name='milestonestatus'), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['admin_users.id'], name=op.f('fk_project_milestones_assignee_id_admin_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_milestones_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_service_id'], ['project_services.id'], name=op.f('fk_project_milestones_project_service_id_project_services'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_project_milestones_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_milestones'))
    )
    op.create_index(op.f('ix_project_milestones_project_id'), 'project_milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_milestones_project_service_id'), 'project_milestones', ['project_service_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='transactiondirection'), nullable=False),
    sa.Column('method', sa.Enum('BANK_TRANSFER', 'CARD', 'CASH', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference_note', sa.Text(), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_transactions_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['admin_users.id'], name=op.f('fk_transactions_recorded_by_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_invoice_id'), 'transactions', ['invoice_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('line_item_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advance_id'], ['advances.id'], name=op.f('fk_payment_allocations_advance_id_advances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_item_id'], ['invoice_line_items.id'], name=op.f('fk_payment_allocations_line_item_id_invoice_line_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_payment_allocations_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    op.create_index(op.f('ix_payment_allocations_line_item_id'), 'payment_allocations', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_transaction_id'), 'payment_allocations', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_allocations_transaction_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_line_item_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_transactions_invoice_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_project_milestones_project_service_id'), table_name='project_milestones')
    op.drop_index(op.f('ix_project_milestones_project_id'), table_name='project_milestones')
    op.drop_table('project_milestones')
    op.drop_index('ix_ledger_entries_project_type', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_project_date', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_file_assets_tenant_id'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_folder_id'), table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index(op.f('ix_advances_tenant_id'), table_name='advances')
    op.drop_index(op.f('ix_advances_client_id'), table_name='advances')
    op.drop_table('advances')
    op.drop_index(op.f('ix_project_services_service_id'), table_name='project_services')
    op.drop_index(op.f('ix_project_services_project_id'), table_name='project_services')
    op.drop_table('project_services')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_project_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('uq_file_folders_tenant_parent_scope_name_project_creator', table_name='file_folders')
    op.drop_index(op.f('ix_file_folders_tenant_id'), table_name='file_folders')
    op.drop_table('file_folders')
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_password_reset_tokens_token_hash', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_invites_token', table_name='invites')
    op.drop_table('invites')
    op.drop_index('ix_client_password_reset_tokens_token_hash', table_name='client_password_reset_tokens')
    op.drop_table('client_password_reset_tokens')
    op.drop_table('client_notes')
    op.drop_index('ix_client_invites_token_hash', table_name='client_invites')
    op.drop_index('ix_client_invites_client_email', table_name='client_invites')
    op.drop_table('client_invites')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_milestone_step_templates_service_id'), table_name='milestone_step_templates')
    op.drop_table('milestone_step_templates')
    op.drop_index('ix_client_users_email', table_name='client_users')
    op.drop_index('ix_client_users_client_id', table_name='client_users')
    op.drop_table('client_users')
    op.drop_index('ix_admin_users_email', table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index('ix_user_activities_user_id', table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_table('tenant_subscriptions')
    op.drop_table('tenant_smtp_configs')
    op.drop_table('tenant_settings')
    op.drop_table('tenant_feature_flags')
    op.drop_index(op.f('ix_services_tenant_id'), table_name='services')
    op.drop_table('services')
    op.drop_index('uq_roles_system_name', table_name='roles', postgresql_where=sa.text('tenant_id IS NULL'))
    op.drop_table('roles')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_notification_preferences_user_id', table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_table('invoice_number_sequences')
    op.drop_index(op.f('ix_clients_tenant_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('plan_feature_defaults')
    op.drop_table('plans')
    op.drop_index('ix_email_verification_tokens_token_hash', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
