"""add_client_clientnote_clientuser_clientinvite

Revision ID: 81cfc015e65d
Revises: 2a3b4c5d6e7f
Create Date: 2026-07-27 15:53:34.311437
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81cfc015e65d"
down_revision: str | None = "2a3b4c5d6e7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "client_type", sa.Enum("COMPANY", "INDIVIDUAL", name="clienttype"), nullable=False
        ),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("billing_address", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tax_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.Enum("ACTIVE", "ARCHIVED", name="clientstatus"), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_clients_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_index(op.f("ix_clients_tenant_id"), "clients", ["tenant_id"], unique=False)
    op.create_table(
        "client_invites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("fk_client_invites_client_id_clients")
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["admin_users.id"],
            name=op.f("fk_client_invites_invited_by_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_client_invites_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_invites")),
    )
    op.create_index(
        "ix_client_invites_client_email", "client_invites", ["client_id", "email"], unique=False
    )
    op.create_index("ix_client_invites_token_hash", "client_invites", ["token_hash"], unique=True)
    op.create_table(
        "client_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["admin_users.id"], name=op.f("fk_client_notes_author_id_admin_users")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("fk_client_notes_client_id_clients")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_notes")),
    )
    op.create_table(
        "client_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_primary_billing_contact", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("fk_client_users_client_id_clients")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_client_users_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_users")),
    )
    op.create_index("ix_client_users_client_id", "client_users", ["client_id"], unique=False)
    op.create_index("ix_client_users_email", "client_users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_client_users_email", table_name="client_users")
    op.drop_index("ix_client_users_client_id", table_name="client_users")
    op.drop_table("client_users")
    op.drop_table("client_notes")
    op.drop_index("ix_client_invites_token_hash", table_name="client_invites")
    op.drop_index("ix_client_invites_client_email", table_name="client_invites")
    op.drop_table("client_invites")
    op.drop_index(op.f("ix_clients_tenant_id"), table_name="clients")
    op.drop_table("clients")
    sa.Enum(name="clienttype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="clientstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
