"""add_purchase_entries

Revision ID: 82a80ee04048
Revises: 7a7ac1a609d0
Create Date: 2026-08-29 22:26:38.736556
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a80ee04048'
down_revision: Union[str, None] = '7a7ac1a609d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], name=op.f('fk_purchase_entries_created_by_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_purchase_entries_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_purchase_entries_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_entries'))
    )
    op.create_index(op.f('ix_purchase_entries_project_id'), 'purchase_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_entries_tenant_id'), 'purchase_entries', ['tenant_id'], unique=False)
    op.create_table('purchase_entry_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_entry_id', sa.Uuid(), nullable=False),
    sa.Column('item_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_entry_id'], ['purchase_entries.id'], name=op.f('fk_purchase_entry_items_purchase_entry_id_purchase_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_entry_items'))
    )
    op.create_index(op.f('ix_purchase_entry_items_purchase_entry_id'), 'purchase_entry_items', ['purchase_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_entry_items_purchase_entry_id'), table_name='purchase_entry_items')
    op.drop_table('purchase_entry_items')
    op.drop_index(op.f('ix_purchase_entries_tenant_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_project_id'), table_name='purchase_entries')
    op.drop_table('purchase_entries')
    # ### end Alembic commands ###
