"""add plan tenant subscription setting feature-flag audit-log admin-user invite tables

Revision ID: dcc0448c5d92
Revises:
Create Date: 2026-07-26 17:40:49.942965
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


def _pg_enum(*args: str, name: str) -> postgresql.ENUM:
    """Build a PostgreSQL ENUM type that skips automatic CREATE TYPE.

    Use when the type is created manually via DO block before table creation.
    """
    e = postgresql.ENUM(*args, name=name, create_type=False)
    e._create_events = False  # noqa: SLF001 — prevents SA from re-creating type
    return e


# revision identifiers, used by Alembic.
revision: str = "dcc0448c5d92"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUM_DEFINITIONS: list[tuple[str, list[str]]] = [
    ("tenantstatus", ["TRIAL", "ACTIVE", "SUSPENDED", "CANCELLED"]),
    ("adminuserrole", ["SUPER_ADMIN", "ADMIN", "MANAGER", "EMPLOYEE"]),
    ("actortype", ["SUPER_ADMIN", "ADMIN_USER", "CLIENT_USER", "SYSTEM"]),
    (
        "permissionlevel",
        ["SUPER_ADMIN_ONLY", "TENANT_ADMIN_EDITABLE", "TENANT_ADMIN_VIEWABLE"],
    ),
    ("subscriptionstatus", ["TRIALING", "ACTIVE", "PAST_DUE", "CANCELLED"]),
    ("billingcycle", ["MONTHLY", "YEARLY"]),
    ("inviterole", ["ADMIN", "MANAGER", "EMPLOYEE"]),
]

ENUM_NAMES = [name for name, _ in ENUM_DEFINITIONS]


def _create_enum_if_not_exists(name: str, values: list[str]) -> None:
    """Create PG enum type idempotently (PG16 compatible DO block)."""
    vals = ", ".join(f"'{v}'" for v in values)
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{name}') THEN
                CREATE TYPE {name} AS ENUM ({vals});
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    # Create enum types first (idempotent)
    for name, values in ENUM_DEFINITIONS:
        _create_enum_if_not_exists(name, values)

    # Build PG ENUM types that skip _on_table_create
    tenantstatus = _pg_enum("TRIAL", "ACTIVE", "SUSPENDED", "CANCELLED", name="tenantstatus")
    adminuserrole = _pg_enum("SUPER_ADMIN", "ADMIN", "MANAGER", "EMPLOYEE", name="adminuserrole")
    actortype = _pg_enum("SUPER_ADMIN", "ADMIN_USER", "CLIENT_USER", "SYSTEM", name="actortype")
    permissionlevel = _pg_enum(
        "SUPER_ADMIN_ONLY",
        "TENANT_ADMIN_EDITABLE",
        "TENANT_ADMIN_VIEWABLE",
        name="permissionlevel",
    )
    subscriptionstatus = _pg_enum(
        "TRIALING", "ACTIVE", "PAST_DUE", "CANCELLED", name="subscriptionstatus"
    )
    billingcycle = _pg_enum("MONTHLY", "YEARLY", name="billingcycle")
    inviterole = _pg_enum("ADMIN", "MANAGER", "EMPLOYEE", name="inviterole")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("max_admin_users", sa.Integer(), nullable=False),
        sa.Column("max_clients", sa.Integer(), nullable=False),
        sa.Column("max_active_projects", sa.Integer(), nullable=False),
        sa.Column("max_storage_mb", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("name", name=op.f("uq_plans_name")),
    )
    op.create_table(
        "plan_feature_defaults",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
            name=op.f("fk_plan_feature_defaults_plan_id_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_feature_defaults")),
        sa.UniqueConstraint("plan_id", "key", name="uq_plan_feature_defaults_key"),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("status", tenantstatus, nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("contact_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("branding", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("logo_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], name=op.f("fk_tenants_plan_id_plans")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", adminuserrole, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_admin_users_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
    )
    op.create_index("ix_admin_users_email", "admin_users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", actortype, nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=255), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_audit_logs_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "tenant_feature_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_feature_flags_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_feature_flags")),
        sa.UniqueConstraint("tenant_id", "key", name="uq_tenant_feature_flags_key"),
    )
    op.create_table(
        "tenant_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=1024), nullable=False),
        sa.Column("permission_level", permissionlevel, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_settings_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_settings")),
        sa.UniqueConstraint("tenant_id", "key", name="uq_tenant_settings_key"),
    )
    op.create_table(
        "tenant_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("status", subscriptionstatus, nullable=False),
        sa.Column("billing_cycle", billingcycle, nullable=False),
        sa.Column("renewal_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
            name=op.f("fk_tenant_subscriptions_plan_id_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_subscriptions_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_subscriptions")),
        sa.UniqueConstraint("tenant_id", name=op.f("uq_tenant_subscriptions_tenant_id")),
    )
    op.create_table(
        "invites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", inviterole, nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["admin_users.id"],
            name=op.f("fk_invites_invited_by_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_invites_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
    )
    op.create_index("ix_invites_token", "invites", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_invites_token", table_name="invites")
    op.drop_table("invites")
    op.drop_table("tenant_subscriptions")
    op.drop_table("tenant_settings")
    op.drop_table("tenant_feature_flags")
    op.drop_table("audit_logs")
    op.drop_index("ix_admin_users_email", table_name="admin_users")
    op.drop_table("admin_users")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_table("plan_feature_defaults")
    op.drop_table("plans")
    # Drop enum types
    for name in ENUM_NAMES:
        op.execute(f"DROP TYPE IF EXISTS {name} CASCADE")
    # ### end Alembic commands ###
